### ISSUE TITLE
Run clippy in CI?

### ISSUE THREAD

**Issue by SUPERCILEX** [bytecodealliance/rustix#456]
There are a number of clippy lints in this repo that may be worth fixing. Has this been considered?

**Comment by sunfishcode** [comment]
My experience contributing PRs to projects that have clippy in CI is that clippy lints frequently change between Rust versions, leading contributors to get CI failures due to clippy lints that are unrelated to the changes they're making.

Also, fixing clippy warnings requires a fair amount of nuance; often, the most obvious way to fix them doesn't result in a net improvement in the code. I do use clippy, and find it useful, but my experience has been that it's most useful when someone choses to run it, and is prepared to carefully consider its suggestions. In CI, it feels like it takes up time and attention in moments where both are precious, without adding sufficient value.

**Comment by SUPERCILEX** [comment]
> My experience contributing PRs to projects that have clippy in CI is that clippy lints frequently change between Rust versions, leading contributors to get CI failures due to clippy lints that are unrelated to the changes they're making.

Lol, yep. We just ran into this over at nix.

> it's most useful when someone chooses to run it, and is prepared to carefully consider its suggestions.

Sadly, that's precisely why it's important to run clippy in CI. Rustix currently spits out tons of existing lints which means I cannot find the lints caused by my changes without difficulty. Perhaps a good balance is to not block PRs on clippy, but still pay attention to them and do monthly cleaning to get back to zero lints?

Or maybe there's a way to run clippy solely on uncommitted changes?

**Comment by sunfishcode** [comment]
I've now submitted #458 which fixes all the clippy lints, at least on some platforms.

As a random datapoint; this exercise didn't find any bugs. It found some things which could be tidier. And I'm happy to tidy things. I don't want clippy hassling people about redundant `&`s when we're focused on other things though.

If you know of ways to set up clippy to only check some changes, or to run in CI in a way that doesn't block (or even notify) PRs but which still gets noticed occasionally by maintainers, I'm open to discussing them. The best option I know of right now is that I'll just try to run clippy a little more often.

**Comment by SUPERCILEX** [comment]
> I've now submitted https://github.com/bytecodealliance/rustix/pull/458 which fixes all the clippy lints, at least on some platforms.

Thank you! Clippy returns no lints for me anymore on the dents branch. :)

> If you know of ways to set up clippy to only check some changes

Unfortunately I don't, so I think the occasional cleaning will have to do.
