### ISSUE TITLE
`Pid::from_raw{,_nonzero}` should not be `unsafe`

### ISSUE THREAD

**Issue by oxalica** [bytecodealliance/rustix#604]
As the docs say,
>  the process it refers to could disappear at any time and be replaced by another, unrelated, process.

It provides no guarantee about the validness of the pid, and is impossible to do so. It's just a wrapper for an non-zero integer. A runtime-invalid `Pid` fed into `pidfd_open` or `kill_process` results in `ESRCH`, without breaking either IO safety or memory safety.

**Comment by sunfishcode** [comment]
I agree about pids. It turns out though what this code is useful for guarding against is negative pid values, which cause functions like `waitpid` and `kill` to behave very differently. That's still not memory or I/O safety though.

So perhaps the real fix is to remove the `unsafe` but make `Pid::from_raw` return an `Option<Self>` so that it can fail if you pass it numbers that would be negative if interpreted as signed.

**Comment by oxalica** [comment]
> ... to remove the `unsafe` but make `Pid::from_raw` return an `Option<Self>`

It already returns `Option<Self>` currently.

> ... would be negative if interpreted as signed.

If so, the underlying type is semantically `i32` not `u32`. We should change `RawPid` to `i32`, and `Pid` to `NonZeroI32` but checked to be non-nagative.
Or is there any platform really support `(i32::MAX as u32 + 1) .. u32::MAX` pids?

**Comment by oxalica** [comment]
Proposed:
```rust
type RawPid = i32;
type RawNonZeroPid = NonZeroI32;

impl Pid {
    // Fail on zero.
    pub const fn from_raw(raw: RawPid) -> Result<Self, ZeroPidError>;
    // No check.
    pub const fn from_raw_nonzero(raw: RawNonZeroPid) -> Self;
}

pub struct ZeroPidError(/* private */());
impl std::error::Error for ZeroPidError {}

impl TryFrom<RawPid> for Pid { type Err = ZeroPidError; }
```

If this is acceptable, I'm happy to make a PR for it.

**Comment by sunfishcode** [comment]
If we just remove `unsafe`, then nothing is guarding against negative pid values. Could we have the functions fail if the user passes a negative value? And maybe have a `from_raw_unchecked` which is safe and doesn't fail, but `debug_assert`s the value isn't negative or so?

Also, since what we're talking about here is an API change, this will need to wait for the 0.38 release. I'll add a note to the planning issue.
