### ISSUE TITLE
Add an implementation of sigaction for libc backend

### ISSUE THREAD

**Issue by notgull** [bytecodealliance/rustix#628]
I wanted to try to reimplement `signal-hook` using `rustix` primitives; see vorner/signal-hook#142. However, to do this we would need `sigaction` and other signal manipulating tools to exist on the `libc` backend as well.

**Comment by sunfishcode** [comment]
Ah, interesting. So this is tricky, because `sigaction` is not a normal syscall. libc implementations of `sigaction` on Linux do more than just call Linux's `rt_sigaction` syscall. They have access to libc internals and do special things for threads.

Also, everything in rustix's public (non-`runtime`) interface can coexist with a libc, but libc's generally assume they're in full control of `sigaction` kinds of syscalls, so invoking the `rt_sigaction` syscall without going through libc could break libc assumptions.

It's possible we can figure something out here, but it'll take some investigation.

**Comment by notgull** [comment]
Interesting! I took a look as `musl`'s implementation and it looked alright to me from this point of view...

**Comment by sunfishcode** [comment]
At a quick glance, it seems musl is doing these things:
 - if the signal number is one of the signals libc internally claims for its own purposes, fail
 - if the signal number is `SIGABRT`, take a lock that is shared with `abort`
 - record all the signals that have custom handlers, so that `posix_spawn` can davoidd "unpredictable and dangerous results"
 - call `SYS_rt_sigprocmask` for internal signals before any custom handlers are installed
 - set `__eintr_valid_flag`, which is used to work around a kernel bug

I'd want to understand those better.

**Comment by sunfishcode** [comment]
I've done some more investigation and updated the comment above with some notes. Some of the issues can be addressed, but I don't see a way to address the others. They are fairly obscure, and it's not clear why libc implementations originally chose to do some of the things they're doing, but ultimately, they are there. If we register signal handlers without going through libc, we'll evoke non-local behavior changes in programs, which I'm not comfortable doing.

**Comment by notgull** [comment]
Yeah, sounds like a bad idea. Thanks for investigating, I'll close this now.

**Comment by polarathene** [comment]
> If we register signal handlers without going through libc, we'll evoke non-local behavior changes in programs, which I'm not comfortable doing.

I am assuming that's specific to a Rust program using libc, but not any interactions between programs? (_which could use different libc, such as glibc vs musl_)

If so, is this something that has been improved upon since the 2023 discussion here? Perhaps via [`eyra`](https://github.com/sunfishcode/eyra#eyra)? (_or one of the crates it builds upon to provide a libc alternative_)
- I see that [`sigaction()` has been implemented](https://github.com/sunfishcode/c-ward/blob/183fd119ca0cc3c63afb8d7c9941952c366f6a77/c-scape/src/signal/mod.rs#L50) within `c-scape`](https://github.com/sunfishcode/c-ward/tree/main/c-scape)
- I'm not too familiar with the lower-level crates used by `eyra`, but I understand for `eyra` itself there are caveats that limit adoption (_none of which seem likely to change_):
- Not all of `libc` implemented
- Only supports static linking
- Requires nightly

**NOTE:** The linked `sigaction` implementation in `c-scape` is dated Sep 2023 in Git blame, other than later change (Mar 2025) to migrate to Rustix 1.0.
