### ISSUE TITLE
"Detecting whether functions are supported at runtime" in docs is misleading

### ISSUE THREAD

**Issue by safinaskar** [bytecodealliance/rustix#665]
https://docs.rs/rustix/0.37.19/rustix/ says: "Things they don’t do include: Detecting whether functions are supported at runtime". But this seams to be not true. Consider this code: https://github.com/bytecodealliance/rustix/blob/bff1d533d898acbdc1ab3d614b66d9e90da66f01/src/backend/libc/fs/syscalls.rs#L454 . Here we do exactly what we promised not to do: we detect in runtime whether statx is supported. If not, we fail back to another function. This is bad for two reasons:

- This contradicts docs
- This will work badly in many container runtimes in Linux. Runtimes usually return EPERM is they don't know this syscall (this often happens if we run new system in old container runtime). But you check here for ENOSYS only, not for EPERM

**Comment by safinaskar** [comment]
It seems it is good idea to use `is_statx_available` here. See also https://lwn.net/Articles/838217/

**Comment by sunfishcode** [comment]
I've submitted https://github.com/bytecodealliance/rustix/pull/666 to add a mention to the docs that rustix does do some feature detection for y2038 and LFS support, and to handle statx returning EPERM so that it falls back to the old non-y2038-safe emulation instead of passing the EPERM on to the user.

If anyone is still using an old container runtime that doesn't permit statx on a 32-bit architecture or mips64, I encourage them to upgrade before the year 2038 gets any closer.

**Comment by safinaskar** [comment]
@sunfishcode , oops, now I see that rustix already supports such broken container runtimes. Now I see comment here: https://github.com/bytecodealliance/rustix/blob/bff1d533d898acbdc1ab3d614b66d9e90da66f01/src/fs/statx.rs#L14-L24 . I missed it. I'm sorry. rustix is _brilliant_!

Also, I think this would be good idea to grep all NOSYS in code and fix other similar places, for example: https://github.com/bytecodealliance/rustix/blob/bff1d533d898acbdc1ab3d614b66d9e90da66f01/src/backend/linux_raw/vdso_wrappers.rs#L258 . Or this: https://github.com/bytecodealliance/rustix/blob/bff1d533d898acbdc1ab3d614b66d9e90da66f01/src/backend/linux_raw/fs/syscalls.rs#L1417

**Comment by safinaskar** [comment]
I didn't tested rustix at all. I don't know whether proper statx detection worked before this pull request, and whether this pull request changed anything. I reported this bug just because I have read sources

**Comment by sunfishcode** [comment]
The patch in https://lwn.net/Articles/838217/ did not end up making it into the Linux tree. glibc and musl in their `faccessat` functions continue to use `faccessat2` and fall back to `faccessat` based only on `ENOSYS` and not `EPERM`. I don't know all the reasons why, but my impression is that people felt that, for `faccessat` at least, probing for `faccessat` was too brittle and that it would be best to just fix the container runtimes.

`prlimit64` is old enough (Linux 2.6.36) that I expect it predates the problematic container runtimes.

The rest of the `ENOSYS` checks are for the various Linux 5.1 64-bit time syscalls on 32-bit platforms. I don't know for sure whether there's actually a problem with those, or if there is, whether it affects anyone. My instinct here is to wait until we have a report of a problem before making any changes here, so that we can test the behavior of any fix.

**Comment by safinaskar** [comment]
@sunfishcode , now I did some experiments (yes, now I did!) and I see that original bug (i. e. problems with detecting bad container runtimes in `rustix::fs::statat`) was fixed in this patch. Let me explain.

I simply found this project (i. e. rustix) in internet. And I saw some code, which (in my opinion) is bad, so I reported this bug. I never actually used rustix. I don't work with 32-bit systems. I use usual x86_64-linux. I'm very sorry for reporting this bug without any actual testing.

So now I decided to actually test something.

My main OS is debian stretch (it is old release). I have old version of systemd-nspawn. But I have modern linux kernel, which supports statx. I created nspawn container with debian sid (this is very new release) inside it. It is not possible to perform statx syscall inside this container (it returns EPERM). So I created small Rust project with rustix inside this container and run it.

Here follows list of variables in my experiment:
- systemd-nspawn vs simple `unshare --mount` (`unshare --mount` doesn't block statx, but systemd-nspawn does)
- libc used in container: glibc vs musl
- x86_64 vs i386
- using feature "use-libc" vs not using it
- using rustix 0.37.19 vs eac93e7c1cfddc2ad795cbdf70be947be7210843
- using `rustix::fs::statx` vs `rustix::fs::statat`

Results are these:
- glibc with i386 (i. e. i386-unknown-linux-gnu) doesn't work at all. Because the very same bug we are talking about (i. e. "_we call statx instead of stat to get 64 bit time on 32 bit system, then we check statx return code for ENOSYS, but container runtime sends us EPERM, and so we fail_") happens inside glibc dynamic linker itself. So I was unable to test rustix in this situation (we fail in dynamic linker before we reach rust's `main`). But i386-unknown-linux-musl works, so I tested rustix there
- `rustix::fs::statx` always works as documented in docs.rs (i. e. here: https://docs.rs/rustix/0.37.19/rustix/fs/fn.statx.html ). I. e. it correctly handles EPERM and translates it to ENOSYS. Both in 0.37.19 and eac93e7c1cfddc2ad795cbdf70be947be7210843
- `rustix::fs::statat` really did not work in 0.37.19 in 32-bit system (i. e. in i386-unknown-linux-musl) in nspawn. And it works now, i. e. in eac93e7c1cfddc2ad795cbdf70be947be7210843. So, yes, original rustix bug now fixed in this commit

So, thanks a lot!
