### ISSUE TITLE
Docs are missing for some APIs

### ISSUE THREAD

**Issue by SUPERCILEX** [bytecodealliance/rustix#974]
For example fork doesn't exist: https://docs.rs/rustix/0.38.28/rustix/runtime/fn.fork.html

**Comment by notgull** [comment]
IIRC the runtime APIs are intentionally undocumented because using them requires a great deal of care and investigation

**Comment by SUPERCILEX** [comment]
Gotya, sounds reasonable.

**Comment by sunfishcode** [comment]
Yes, the whole `runtime` module is `#[doc(hidden)]`. Many of the functions, including `fork`, aren't just `unsafe`, but are impossible to use safely unless you are implementing libc yourself. That's because the libc `fork` API includes things like calling the `pthread_atfork` callbacks, which can't be done by any library other than the one that implements `pthread_atfork`.

That said, I could see a place for an API that just wraps `libc` and provides somewhat higher-level API, but my sense is, that that should ideally be a separate crate, because it wouldn't need any of rustix's backend infrastructure, as it would always just call libc.
